server:
  port: 8088

spring:
  application:
    name: reservation-service
  datasource:
    url: ${RESERVATION_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.ndaje.reservation: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

application:
  config:
    user-service-url: http://localhost:8082
    trip-service-url: http://localhost:8084
