<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.1</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.ndaje</groupId>
	<artifactId>ndaje-app-backend</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>ndaje-app-backend</name>
	<description>Backend microservices pour Ndaje App</description>
	
	<modules>
		<module>eureka-server</module>
		<module>api-gateway</module>
		<module>trip-service</module>
		<module>reservation-service</module>
		<module>user-service</module>
		<module>document-service</module>
	</modules>

	<properties>
		<java.version>17</java.version>
		<spring-cloud.version>2023.0.0</spring-cloud.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!-- ajoute devtools -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-devtools</artifactId>
				<scope>runtime</scope>
				<optional>true</optional>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>io.github.cdimascio</groupId>
			<artifactId>dotenv-java</artifactId>
			<version>3.2.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<environmentVariables>
						<KEYCLOAK_SERVER_URL>${KEYCLOAK_SERVER_URL}</KEYCLOAK_SERVER_URL>
						<KEYCLOAK_REALM>${KEYCLOAK_REALM}</KEYCLOAK_REALM>
						<KEYCLOAK_ADMIN_CLIENT_ID>${KEYCLOAK_ADMIN_CLIENT_ID}</KEYCLOAK_ADMIN_CLIENT_ID>
						<KEYCLOAK_ADMIN_CLIENT_SECRET>${KEYCLOAK_ADMIN_CLIENT_SECRET}</KEYCLOAK_ADMIN_CLIENT_SECRET>
						<DB_USERNAME>${DB_USERNAME}</DB_USERNAME>
						<DB_PASSWORD>${DB_PASSWORD}</DB_PASSWORD>
						<USER_DB_URL>${USER_DB_URL}</USER_DB_URL>
						<TRIP_DB_URL>${TRIP_DB_URL}</TRIP_DB_URL>
						<RESERVATION_DB_URL>${RESERVATION_DB_URL}</RESERVATION_DB_URL>
						<R2_ACCOUNT_ID>${R2_ACCOUNT_ID}</R2_ACCOUNT_ID>
						<R2_ACCESS_KEY>${R2_ACCESS_KEY}</R2_ACCESS_KEY>
						<R2_SECRET_KEY>${R2_SECRET_KEY}</R2_SECRET_KEY>
						<R2_BUCKET>${R2_BUCKET}</R2_BUCKET>
						<R2_ENDPOINT>${R2_ENDPOINT}</R2_ENDPOINT>
					</environmentVariables>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
