server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route Trip Service
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trips/**

        # Route User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/admin/**

        # Route Document Service
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**

        # Route Reservation Service
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
